# Generated by Django 2.2 on 2021-06-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('order', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('SURVEY', 'SURVEY'), ('DISCUSSION', 'DISCUSSION'), ('DIARY', 'DIARY')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tiles.Tile')),
            ],
        ),
    ]
