# Generated by Django 2.2 on 2021-06-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created', 'pk']},
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
