# Generated by Django 2.2 on 2021-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('status', models.CharField(choices=[('LIVE', 'LIVE'), ('PENDING', 'PENDING'), ('ARCHIVED', 'ARCHIVED')], max_length=8)),
            ],
        ),
    ]
