# Generated by Django 2.2 on 2021-06-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ['launch_date', 'pk']},
        ),
    ]
